-- Run this entire file in Supabase:
-- SQL Editor → New query → paste → Run.

create table if not exists public.sends (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid()
    references auth.users(id) on delete cascade,
  gym_crag text not null,
  sent_on date not null,
  route text default '',
  grade text not null check (
    grade in (
      '5a', '5a+', '5b', '5b+', '5c', '5c+',
    '6a', '6a+', '6b', '6b+', '6c', '6c+',
    '7a', '7a+', '7b', '7b+', '7c', '7c+', 
    '8a', '8a+', '8b', '8b+', '8c', '8c+', 
    '9a', '9a+', '9b', '9b+', '9c', '9c+'
    )
  ),
  ascent_type text not null check (
    ascent_type in ('RP', 'FL', 'OS')
  ),
  style text not null check(
    style in ('TR', 'LD')
  ),
  created_at timestamptz not null default now()
);

alter table public.sends enable row level security;

create policy "Users can view their own sends"
on public.sends
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can add their own sends"
on public.sends
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their own sends"
on public.sends
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete their own sends"
on public.sends
for delete
to authenticated
using ((select auth.uid()) = user_id);
